name: github pages

on:
  push:
    branches:
      - dev # dev to get the action right, remove when 
      - master  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'    steps:
   
      - name: Setup pdoc
        run: |
          python -m pip install --upgrade pip
          pip install pdoc

      - name: Build docs with pdoc
        run: | 
          mkdir -p docs
          pdoc --config latex_math=True --html -o docs --force litho1pt0 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY_PR_KEY }}
          publish_dir: docs/litho1pt0